### ISSUE TITLE
三角形的最小路径和dp方法这里，循环次数应该是triangle[i].length-1

### ISSUE THREAD

**Issue by minicloudsky** [allentofight/easy-cs#1]
https://github.com/allentofight/easy-cs/blob/main/%E7%AE%97%E6%B3%95/%E4%B8%80%E6%96%87%E5%AD%A6%E4%BC%9A%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E8%A7%A3%E9%A2%98%E6%8A%80%E5%B7%A7.md
![image](https://user-images.githubusercontent.com/32286819/110230621-326ac700-7f4d-11eb-84f7-24f4839d7823.png)
数组长度是4，这里循环到triangle[i].length时候，数组mini长度是4，下标会越界，建议修改为 triangle[i].length-1

**Comment by allentofight** [comment]
你是对的，已修正，非常感谢指出！
